# Generated by Django 3.2 on 2021-04-19 04:22

import django_postgres_unlimited_varchar
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=56, verbose_name="HTTP Method")),
                (
                    "path",
                    django_postgres_unlimited_varchar.UnlimitedCharField(
                        verbose_name="Incoming path"
                    ),
                ),
                ("params", models.JSONField(null=True, verbose_name="Query params")),
                ("json", models.JSONField(null=True, verbose_name="Json data")),
                ("data", models.TextField(verbose_name="Raw data")),
                ("headers", models.JSONField(verbose_name="Request headers")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
            ],
        ),
    ]
