# Generated by Django 3.1 on 2023-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook_catcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookdata",
            options={"verbose_name": "Webhook Data", "verbose_name_plural": "Webhooks Data"},
        ),
        migrations.AlterField(
            model_name="webhookdata",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
